server:
  port: 8081
spring:
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  app名称
  application:
    name: demo-handTemplate
  #  启用的配置文件
  profiles:
    active:
      - dev

# mybatis
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    com.hand.demo.template_44294: warn
    mybatis: warn

